n = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('Só tem espaço ? ', n.isspace())
print('È um numero ?', n.isnumeric())
print('É alfabetico ?', n.isalpha())
print('É alfanumerico ?', n.isalnum())
print('É maiuscula ?', n.isupper())
print('É minuscula ?', n.islower())
print('É capitalizada ?', n.istitle())